name: tests
defaults:
  run:
    shell: bash

on:
  push:
    branches: [ main ]
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
  schedule:
    - cron: '25 11 * * *'
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run with tmate enabled'
        type: boolean
        required: false
        default: false

jobs:
  tests:
    strategy:
      matrix:
        ddev_version: [ stable, HEAD ]
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
        with:
          limit-access-to-actor: true

      - name: Install ddev
        uses: ddev/github-action-add-on-test@v2
        with:
          ddev_version: ${{ matrix.ddev_version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          addon_repository: ${{ github.repository }}
          addon_ref: ${{ github.ref }}
          debug_enabled: ${{ inputs.debug_enabled }}
